### ISSUE TITLE
_modded Gamemodes Not Being Listed Correctly in In-Game Server Browser

### ISSUE THREAD

**Issue by Hazbelll** [danielga/gmsv_serversecure#96]
### Details
Servers utilising this module that run a _modded Gamemode, [as documented on the Wiki](https://wiki.facepunch.com/gmod/Gamemode_Creation#moddinggamemodes) do not show up in the In-Game Server browser under the original, correct gamemode category. Instead, they show up under a [new, duplicated gamemode category](https://i.imgur.com/J447VHI.png).

Originally I thought this was an issue with the game itself as I know somebody who had similar issues with _modded gamemodes in the past, [so I reported it here](https://github.com/Facepunch/garrysmod-issues/issues/5403), but Rubat was unable to reproduce it and from further digging, I realised this module was the culprit as once removed, the correct behaviour returned.

Tested Server Version (Main):
```
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 18:26:23 Jan  9 2023 (8829) (4000)
GMod version 2023.02.10, branch: unknown
Windows 32bit Dedicated Server
```

Tested Client Version (x86-64):
```
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 10:53:50 May 30 2022 (8605) (4000)
GMod version 2022.07.13, branch: x86-64, multicore: 1
Windows 64bit
```

Also Tested Client Version (Main):
```
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 18:26:23 Jan  9 2023 (8829) (4000)
GMod version 2023.02.10, branch: unknown, multicore: 0
Windows 32bit
```
### Steps to reproduce

1. Ensure this module is installed correctly and active on the server.
2. On the server, copy the [`sandbox` gamemode folder](https://github.com/Facepunch/garrysmod/tree/master/garrysmod/gamemodes/sandbox) and its contents to `addons/my_gamemode/gamemodes/`.
3. Rename the `sandbox` gamemode folder to `sandbox_modded` and rename the `sandbox.txt` inside it to `sandbox_modded.txt`.
4. Set the server's `+gamemode` parameter to `+gamemode sandbox_modded` and start the server.
5. On the client, check which gamemode category the server gets listed under in the in-game server browser.

**Comment by Kefta** [comment]
Confirmed.

**Comment by danielga** [comment]
I believe this should be fixed in [version 1.5.42](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.41-rc1).

**Comment by Hazbelll** [comment]
Thank you for the update. Unfortunately, the issue remains when using the updated 1.5.42 binary (Sidenote: The link you provided takes you to the release page for 1.5.4**1**).

Tested the Windows binary with both Server/Client using the "main" branch of the game. End result is the same as before.

**Comment by danielga** [comment]
Think I tested it incorrectly. Gave it another pass, changed the logic, and tested. [I think now it's working.](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.42-rc2)

**Comment by Hazbelll** [comment]
Thank you again. I can confirm (On Windows at least, both Server/Client using the "Main" branch) that the issue is now resolved with `1.5.42-rc2`!
